### ISSUE TITLE
Doesn't seem to work with window.print

### ISSUE THREAD

**Issue by FredyC** [gregnb/use-detect-print#1]
When trying to initiate printing with `window.print()`, the hook is not re-executed and preview is shown as if not printing. Printing through regular browser shortcut works though. I wonder why is it so different.

I even tried `setTimeout(window.print, 0)` so React has a chance to re-render, but that totally kills the browser tab for some reason.

**Comment by sibelius** [comment]
any workaround for this?

**Comment by sibelius** [comment]
what about removing the `[]` from the hook?

```
useEffect(() => {
    const printMq = typeof window !== 'undefined' && window.matchMedia && window.matchMedia('print');
    const mqEvent = mqList => toggleStatus(!!mqList.matches);

    printMq.addListener(mqEvent);
    return () => printMq.removeListener(mqEvent);
  }, );
```

**Comment by jdeol** [comment]
Check out : https://github.com/facebook/react/issues/16734
